"""
********************************************************************************
compas_mobile_robot_reloc
********************************************************************************

.. currentmodule:: compas_mobile_robot_reloc
"""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from os import path

import compas.plugins

PKG_ROOT = path.dirname(__file__)
REPO_ROOT = path.abspath(path.join(PKG_ROOT, ".."))


def _get_version():
    # from https://smarie.github.io/python-getversion/#package-versioning-best-practices
    # and setuptools_scm docs
    try:
        # import from _version.py generated by setuptools_scm during release
        from ._version import version

        return version
    except ImportError:
        from importlib.metadata import PackageNotFoundError
        from importlib.metadata import version

        try:
            return version("rapid-clay-formations-fab")
        except PackageNotFoundError:
            # package is not installed
            pass

    return "src"


@compas.plugins.plugin(category="install")
def installable_rhino_packages():
    return ["compas_mobile_robot_reloc"]


__author__ = "Gramazio Kohler Research"
__copyright__ = "2020 Gramazio Kohler Research"
__license__ = "MIT License"
__email__ = "anton@tetov.se"
__version__ = _get_version()


__all_plugins__ = ["compas_mobile_robot_reloc.rhino_install"]
