"""
********************************************************************************
total_station_robot_localization
********************************************************************************

.. currentmodule:: total_station_robot_localization
"""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from os import path

PKG_ROOT = path.dirname(__file__)
REPO_ROOT = path.abspath(path.join(PKG_ROOT, ".."))

# from https://smarie.github.io/python-getversion/#package-versioning-best-practices
try:
    # -- Distribution mode --
    # import from _version.py generated by setuptools_scm during release
    from ._version import version as __version__
except ImportError:
    try:
        # -- Source mode --
        # use setuptools_scm to get the current version from src using git
        from setuptools_scm import get_version

        __version__ = get_version(REPO_ROOT)
    except ImportError:
        __version__ = "src"

__author__ = "Gramazio Kohler Research"
__copyright__ = "2020 Gramazio Kohler Research"
__license__ = "MIT License"
__email__ = "anton@tetov.se"
